name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy_to_render:
    runs-on: ubuntu-latest

    env:
      SECRET_URL: ${{ secrets.SECRET_URL }}

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Trigger Render Deploy
        run: |
          curl -X POST $SECRET_URL