name: CI test control

on:
  pull_request:
    branch: [ addtests ]

jobs:
  run_test:
    runs-on: ubuntu-latest

    env:
      ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      DATABASE_TOKEN: ${{ secrets.DATABASE_TOKEN }}

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: install node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: clean install
        run: npm ci

      - name: prettier check
        run: npm run prettier:check

      - name: ESLint
        run: npm run lint

      - name: run tests
        run: npm run test
      

